services:
  - docker:dind
variables:
  DOCKER_HOST: tcp://docker:2375

stages:
  - test
  - deploy

codeception:
  image: docker:stable
  artifacts:
    expire_in: 1 week
    when: on_failure
    paths:
      - tests/_output/*.png
  stage: test
  script:
    - apk add --no-cache py-pip python-dev libffi-dev openssl-dev gcc libc-dev make
    - cp docker-compose.dev.yml docker-compose.yml
    - pip install docker-compose
    - docker-compose up -d
    - docker exec akppro_php_1 composer install
    - docker exec akppro_php_1 mysql -uroot -proot -h mysql -e "SET GLOBAL sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY',''));"
    - docker exec akppro_php_1 cp config/db.docker.php config/db.test.php
    - docker exec akppro_php_1 cp config/db.docker.php config/db.php
    - docker exec akppro_php_1 cp tests/acceptance.suite.ci.yml tests/acceptance.suite.yml
    - docker exec akppro_php_1 tests/bin/yii migrate --interactive=0
    - docker exec akppro_php_1 vendor/bin/codecept run


