version: '2'
services:
  selenium:
    image: selenium/standalone-chrome
  mysql:
    image: mysql:5.7
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/config.cnf:/etc/mysql/conf.d/config.cnf
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: yii2
      MYSQL_PASSWORD: database
  php:
    image: yiisoftware/yii2-php:7.1-apache
    environment:
      YII_DEBUG: 'true'
      YII_ENV: 'dev'
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8081:80'