version: '2'
services:
  selenium:
    image: selenium/standalone-chrome
  mysql:
    image: mysql:5.7
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/config.cnf:/etc/mysql/conf.d/config.cnf
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: yii2
      MYSQL_PASSWORD: database
  nginx:
    image: nginx
    volumes:
      - ./:/app:delegated
      - ./docker/nginx_conf.d:/etc/nginx/conf.d/
    ports:
      - '8081:80'
  php:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      YII_DEBUG: 'true'
      YII_ENV: 'prod'
    volumes:
      - ./:/app:delegated