#!/bin/bash
cp docker-compose.dev.yml docker-compose.yml
cp config/db.docker.php config/db.php
cp config/db.docker.php config/db.test.php
cp tests/acceptance.suite.ci.yml tests/acceptance.suite.yml
docker-compose up -d
docker exec php_1 composer install -vv
docker exec php_1 ./yii migrate --interactive=0